### ISSUE TITLE
to register our company on your database

### ISSUE THREAD

**Issue by ham-di** [chrieke/awesome-geospatial-companies#1]
our company is pixel geo-information consulting plc from Ethiopia Addis Ababa and we are focused on GIS Workflow Automation, GIS analysis, Surveying, and environmental research.

**Comment by chrieke** [comment]
@ham-di Thank you! Will add in the next iteration.

**Comment by chrieke** [comment]
@ham-di Could you provide me the name & website of the company?

**Comment by chrieke** [comment]
Closing for now, let me know if you have any more infos!
