### ISSUE TITLE
Update-SIRS

### ISSUE THREAD

**Issue by aurelienchaumet** [chrieke/awesome-geospatial-companies#12]
Really great collection thanks a lot for this work !
Maybe you could add SIRS from France in it ?

https://www.sirs-fr.com/sirs/en/
Size : M
Category : GIS Spatial analysis
Description : the company has been producing geographical data based on satellite and airborne platforms (aircraft and drones) but also in situ measurements
City : Villeneuve d'Ascq
Adress : 27 Rue du Carrousel

**Comment by chrieke** [comment]
Hi @aurelienchaumet, thanks for the info. SIRS is already on the list under France. Thank you!
