### ISSUE TITLE
New company; ConstellR

### ISSUE THREAD

**Issue by NiklasJordan** [chrieke/awesome-geospatial-companies#18]
Company: ConstellR (https://constellr.space/)
Country: Germany
Office Size: S
Focus: 🌐 GIS / Spatial Analysis (Global Temperature Monitoring)
Adress: Ernst-Zermelo-Str. 4, 79104 Freiburg, Germany

**Comment by chrieke** [comment]
Thank you @NiklasJordan , added to the iteration that will be updated later today.
