### ISSUE TITLE
EO companies list + smaller fixes

### ISSUE THREAD

**Issue by DahnJ** [chrieke/awesome-geospatial-companies#25]
Hi, first of all, thanks for this list, it's been immensely useful to me many times already!

### Companies not on the list

During preparing my own list of EO companies and their job sites ([EO-jobs](https://github.com/DahnJ/EO-jobs)), I stumbled upon the following companies that could be added to the list.

- [Aerospacelab](https://www.aerospacelab.be/)
- [Arlula](https://www.arlula.com/)
- [Arturo](https://arturo.ai/)
- [Axelspace](https://www.axelspace.com/)
- [Blue River](https://bluerivertechnology.com/)
- [Bluefield](https://bluefield.co/)
- [Capella Space](https://capellaspace.com/) 
- [ClimateX](https://www.climate-x.com/)
- [Climavision](https://www.climavision.com/)
- [Earth Blox](https://www.earthblox.io/)
- [GeoOptics](https://geooptics.com/)
- [Hawkeye360](https://www.he360.com/)
- [HySpecIQ](https://hyspeciq.com/)
- [iQPS](https://i-qps.net/)
- [Katrisk](https://www.katrisk.com/)
- [Kawa space](https://www.kawa.space/)
- [Kleos](https://kleos.space/)
- [KP labs](https://kplabs.space/)
- [Near space labs](https://nearspacelabs.com/)
- [Orbital sidekick](https://orbitalsidekick.com/)
- [Pachama](https://pachama.com/)
- [Predasar](https://www.predasar.com/)
- [Promethee](https://www.promethee.earth/en/home/)
- [Regrow](https://www.regrow.ag/)
- [Satsearch](https://satsearch.co/)
- [Satsure](https://satsure.co/)
- [SkyFi](https://skyfi.com/)
- [Space will](http://en.spacewillinfo.com/)
- [Spacesense](https://www.spacesense.ai/)
- [Spacety](https://en.spacety.com/)
- [Spiral blue](https://www.spiralblue.space/)
- [Spire](https://spire.com/)
- [Tomorrow.io](https://www.tomorrow.io/)
- [Umbra](https://umbra.space/)
- [Unseenlabs](https://umbra.space/)
- [World From Space](https://worldfrom.space/)

### Fixes

There are also a few small fixes:

- Overstory is not located in "Amsterdamn" :grin: 
- Targomo's main office is actually its Berlin office (website currently states Alexanderstraße 5, 10178 Berlin), that's where most people work (source: I have worked for them).
- Extraneous colon in developmentseed's Washington address
- Sylvera's "city" column simply says "UK"

I might try to help with filling those in later, but either way, I thought I would at least share this list for now.

**Comment by chrieke** [comment]
Oh wow that is fantastic @DahnJ thank you very much!

**Comment by chrieke** [comment]
Added most of them. A few still left that seemed to be very early stage with a only a teaser page, and a few more hardware manufacturers which is always tricky to include on the list. Will revisit in a few weeks and keep it open till then. Thanks agains, so many cool companies!

**Comment by chrieke** [comment]
Closing, next update coming soon.

**Comment by dvinouze** [comment]
Hi,
The link to [Unseenlabs](https://umbra.space/) is wrong, it seems to be [Unseenlabs](https://unseenlabs.space/)
