### ISSUE TITLE
OneSoil now in Switzerland!

### ISSUE THREAD

**Issue by gakarak** [chrieke/awesome-geospatial-companies#26]
OneSoil move company into Switzerland. 
Address **seefeldstrasse 123 8008 Zurich Switzerland**

And we increase size of the company form S to M
i added comments in google-sheet:

- Country: Switzerland
- Office Size: M
- City: Zurich
- Address: Seefeldstrasse 123 8008 Zurich Switzerland

**Comment by chrieke** [comment]
Changed in next update, thank you!
