### ISSUE TITLE
List from GeoBusiness

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#27]
I was at the GeoBusiness conference in London this week, and saw some companies that were exhibiting that are not in the list:

- [Ordnance Survey](https://www.ordnancesurvey.co.uk/)
- [Echo Analytics](https://echo-analytics.io/) 
- [Fugro](https://www.fugro.com/)
- [Geo4D](https://www.geo-4d.com/)
- [GeoCue](https://geocue.com/)
- [Geolantis.360](https://www.geolantis.com/)
- [what3words](what3words.com)
- [Landmark](https://www.landmark.co.uk/)
- [Pix Pro](https://www.pix-pro.com/)
- [SatSense](https://satsense.com/)
- [Vercator](https://vercator.com/)

And a couple of others off the top of my head:
- [SafeGraph](https://www.safegraph.com/)
- [UnaCast](https://www.unacast.com/)
- [Foursquare](foursquare.com)
- [GeoIQ](https://geoiq.io/)
- [GlobalTrust](https://globaltrustgrp.com/)
- [CityMapper](https://citymapper.com/)
- [Blis](https://blis.com/about-us/)
- [Global Canopy](https://globalcanopy.org/)

I hope these are relevant for this list. Happy to continue adding if these suggestions are useful! (Also thank you so much for this list, it helped hugely for my last job search)

**Comment by chrieke** [comment]
Oh wow! Thank you @dchirst for the suggestions and kind words. Added almost all of them for the next update. Focus was on commercial companies so no research institutes \ government agencies yet, will think about how this could be integrated.
