### ISSUE TITLE
Add companies from Global top 100 Geospatial Companies 2022

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#28]
I found [this list from GeoAwesome](https://geoawesomeness.com/global-top-100-geospatial-companies-2022-edition/) for the top Geospatial companies in 2022. There seem to be a few that aren't in this list, such as Avuxi and Cesium. Could be a good idea to add these?

**Comment by chrieke** [comment]
Added some to the next update, thank you!
