### ISSUE TITLE
A Few more Geospatial Companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#29]
- [zenly](https://zenly.com/) - a _trendy_ social mapping platform for Gen Z (owned by Snap)
- [Earthsense](https://www.earthsense.co.uk/) - air quality mapping
- [MapTiler](https://www.maptiler.com/) - maps for developers
- [PLACE](https://www.thisisplace.org/) - Airborne mapping of cities
- [NCX](https://ncx.com/) - carbon credits backed up by GIS
- [Placemark](https://placemark.io) - collaborative online mapping software
- [Geovation](geovation.uk) - Geospatial startup accelerator. Spin off from Ordnance Survey, so sort-of government? But OS is no longer a government agency, so I'll leave that decision up to you
- [CalTopo](https://caltopo.com/about/who-we-are) - GIS company
- [TravelTime](https://traveltime.com/) - seems to be a startup doing route apis
- [Salo Sciences](https://salo.ai/) - another GIS carbon credits company
- [Deep Planet](https://www.deepplanet.ai/) - AgTech focusing on wine

Also, Earth-i shouldn't be described as a future satellite constellation any more - they'd better be described as 🌎 AI-powered satellite analytics (source, used to work for Earth-i)

<br class="Apple-interchange-newline">
</body>
</html>

Cheers!

**Comment by chrieke** [comment]
Added almost all. NCX is rebranded Silviaterra, super interesting to see their development. Thanks again Dan so much!
