### ISSUE TITLE
Added a couple more space companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#32]
* [Advanced Infrastructure](https://www.advanced-infrastructure.co.uk/) - geospatial startup doing energy infrastructure mapping
* [Ellipsis Drive](https://ellipsis-drive.com/) - Like Dropbox for spatial data
* [TerraGo](https://terragotech.com/) - "Intelligent Field Software"

Cheers,

Dan

**Comment by chrieke** [comment]
Thank you very much!
