### ISSUE TITLE
Some new companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#36]
* [Space4Good](https://www.space4good.com/about-us) - B-Corporation using EO data for humanitarian and environmental projects
* [Envitia](https://www.envitia.com/) - General GIS/EO/Geospatial provider? (I can't stand EO companies' websites, it's always so vague. Like "The Power of Where", "Unlocking the Geospatial Potential")
* [Kaart](https://www.kaart.com/) - General geospatial
* [Pharos](https://www.pharossoftware.com/) - API for geospatial data.
* [Spatial Days](https://spatialdays.com/) - Spatial consultancy

Merry christmas! 🎄

**Comment by chrieke** [comment]
Added, thanks so much @dchirst Happy holidays to you too!
