### ISSUE TITLE
New Geospatial Companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#44]
Hey Christoph!

I have found a few more companies on my journeys around the internet:
* [SGA](https://sga.ai/) - an agriculture Geospatial AI platform
* [Earthrise Media](https://earthrise.media/) - an environmental digital agency, uses a tonne of geospatial data
* [Intellync](https://intellync.com/) - Another geospatial agriculture offering
* [Ryder Geospatial](https://www.rydergeospatial.ie/) - mapping services in Ireland
* [Remotely360](https://remotely360.com/) - Remote sensing consultancy
* [Geosyntec Consultants](https://www.geosyntec.com/) - geospatial consultancy
* [EveryPoint](https://everypoint.io/) - Asset monitoring
* [StockPile Reports](https://www.stockpilereports.com//) - also asset monitoring (same company maybe?)
* [Exodus Orbitals](https://exodusorbitals.com/) - space based computing, has a lot of EO use cases tho
* [WorldSphere](https://worldsphere.ai/) - hurricane prediction
* [LandBanking Group](https://thelandbankinggroup.com) - Nature Remote sensing
* [ModoPlus](https://www.modoplus.de) - PropTech company with geospatial bent
* [Zesty.ai](https://zesty.ai) - Insuretech through geo
* [OsmAnd](https://osmand.net) - Open Street Map client
* [Foursquare](https://location.foursquare.com) - Location intelligence platform
* [EarthMover](https://earthmover.io) - Cloud data stack for science
* [Anyways](https://www.anyways.eu/map/?#8.13/51.046/3.954) - Mobility map
* [Loam Bio](https://www.loambio.com/?utm_source=substack&utm_medium=email) - AgTech to boost soil carbon
* [Risilience](https://risilience.com/?utm_source=substack&utm_medium=email) - Climate Risk
* [Nadar](https://www.nadar.earth/)  - Forest monitoring

I'm also currently working through the current list of geo companies and making  notes where there are currently mistakes! I'll have another issue for you there in the coming weeks. 

Cheers,

Dan

**Comment by chrieke** [comment]
Thank you again and again! Added most, some added in new [issue](https://github.com/chrieke/awesome-geospatial-companies/issues) to come back to.

For your own job list:
- Remotely seems defunct, noone on linkendin and last tweet from 2020.
- Stockpile Reports seems indeed the same as Everypoint, same address also.
