### ISSUE TITLE
Out-of-date info for various companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#48]
Hey @chrieke ,

I've been going through all the companies on the list, and found a few which have some out of date information:

- Finitie Carbon should be Finite Carbon
- GBS has been duplicated - it's the same company as Geographic Business Solutions
- Geoplex got bought by Nova systems
- GeoSpark is now Seerist
- GeoSys is now EarthDaily
- GIS People has been accidentally duplicated,  despite being the same office
- Granular is now Corteva
- http://grupoengemap.com.br/ - doesn't work
- http://www.imgeospatial.com/ doesn't work
- Cloud to Street is now Floodbase
- [Maydai.ai](http://maydai.ai/) website doesn't work
- Precisely is multinational and has a bunch of offices
- Propeller Aero has other offices
- [IIS Windows Server](http://www.quantumasia.in/) - doesn't work
- Quantum Spatial is now NV5
- rapid lasso website is now [Start](https://rapidlasso.de/)
- Scanworld has been bought by Constellr
- SigmaSpace is now Hexagon
- SIRS has been bought by CLS
- Southern Mapping has been bought by Woolpert
- Spatial Networks is now Fulcrum
- [Tecterra's website](https://tecterra.com.br) no longer works
- Unfolded AI has been bought by Foursquare
- Utilis has been bought by Asterra

I hope this is useful! thanks so much

**Comment by chrieke** [comment]
Yeah I'm pretty sure this IS USEFUL!!! 💯 :) thanks so much, currently without a laptop but will edit it next weekend.

**Comment by chrieke** [comment]
Included most info! Some urls are flaky, now most worked. Thank you again @dchirst, awesome work!
