### ISSUE TITLE
A couple more companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#52]
From my travels around the internet:
- https://swiftgeospatial.solutions/
- https://www.pointr.tech/
- https://www.picarro.com/
- https://raptormaps.com/
- https://woov.com/ (this one i'm not sure about, they make maps for festivals? Does that count as geospatial?)
- https://www.mierune.co.jp/?lang=en
- www.mappedin.com
- https://globalcanopy.org/
- https://periegesis.com/
- https://www.onxmaps.com/
- https://geoalert.io/
- https://www.gis-e.org/
- https://www.informed.com/
- https://www.tblx.io/
- https://nuview.space/
- https://rgi-corp.com/
- https://ecere.com/

Cheers!

**Comment by chrieke** [comment]
New chapter for Uzbekistan!!

Added around half for now, other ones have to come back to and see if relevant for the list, keeping track here https://github.com/chrieke/awesome-geospatial-companies/issues/50#issuecomment-1585160570
