### ISSUE TITLE
Few more companies :)

### ISSUE THREAD

**Issue by seedlit** [chrieke/awesome-geospatial-companies#53]
| Company | Office Size | Country | Category | Focus | Website | City | 
| --- | --- | --- | --- | --- | --- | --- |
| Data From Sky | S | Czech Republic | UAV / Aerial | Traffic Analysis | https://datafromsky.com/ | Brno |
| Land Hawk | S | UK | GIS / Spatial Analysis |  | https://www.landhawk.uk/ | Swindon |
| Unearth | M | USA | GIS / Spatial Analysis |  | https://www.unearthlabs.com/ | Seattle |
| Woven Planet | L | Japan | Webmap / Cartography | Mobility Solutions/ Automated Mapping | https://www.woven-planet.global/ | Tokyo |
| Enview | L | USA | GIS / Spatial Analysis | 3D Automation | https://enview.com/ | San Diego |
| Local Data | S |  | Webmap / Cartography | | http://localdata.com/ |  |
| SkyQraft | M | Sweden | GIS / Spatial Analysis | Grid insights | https://www.skyqraft.com/ | Stockholm |
| UrbanSim | S | USA | GIS / Spatial Analysis | Urban Development Planning | https://www.urbansim.com/ | Seattle |
| Boomerang Geospatial | S |  | GIS / Spatial Analysis | Teaching and Training | http://www.boomgeo.com/ | |
| FirmaTek | M | USA | GIS / Spatial Analysis |  | https://firmatek.com/ | San Antonio |
| AgEagle | M | USA | GIS / Spatial Analysis | Drones and Drone Operation Software | https://ageagle.com/ | Wichita |
| NextBillion | L | Singapore | Webmap / Cartography | Mapping Platform | https://nextbillion.ai/ | Singapore |
| ClimateAI | M | USA | Earth Observation | Climate Insights | https://climate.ai/ | San Francisco |
| TerraScope |  | Belgium | Earth Observation | Satellite Imagery | https://terrascope.be/en | Mol |
| Univrses | M | Sweden | Webmap / Cartography | AI generated maps | https://univrses.com/ | Stockholm |
| Senterta | L | USA | Digital Farming | Ag drones and analytics | https://sentera.com/ | St Paul |
| OpenAQ | S | USA | Earth Observation | Air Quality Data | https://openaq.org/ | Washington |
| NovaSystems | L | UK | Earth Observation | | https://www.novasystems.com/uk |  |
| MyEasyFarm | M | France | Digital Farming | Precision Agriculture| https://www.myeasyfarm.com/en/ | Bezannes |
| Wegaw | S | Switzerland |Earth Observation | Snow Datasets | https://wegaw.com/| Lausanne |
| SoilWatch | S | Finland |Earth Observation| Agriculture | https://soilwatch.eu/| Helsinki|
| Visicom | M | Ukraine |Webmap / Cartography| Digital Twin | https://visicomdata.com/ | Kyiv |
| RockRobotic | S | USA | GIS / Spatial Analysis | Lidar and 3D map processing | https://www.rockrobotic.com/ | Mountain View |
| Teren | M | USA | GIS / Spatial Analysis | 3D | https://www.teren4d.com/ | Lakewood |
| BlackShark | M | Austria | GIS / Spatial Analysis | 3D Digital Twin | https://blackshark.ai/ | Graz |
| Cervest | L | England | GIS / Spatial Analysis | Climate Intelligence | https://cervest.earth/ | London |
| DAS | M | Australia | GIS / Spatial Analysis | Agriculture | https://digitalagricultureservices.com/ | Melbourne |
| GeoSat | M | Portugal | Satellite Operator | Satellite Data and Analytics | https://geosat.space/ | Lisbon |
| Adatos | S | Singapore | Earth Observation | Carbon quantification and Agriculture | https://www.adatos.com/ | Singapore |
| Kitware | L | USA | GIS / Spatial Analysis  | | https://www.kitware.com/ | New York |
| Skyfi | M | USA | Satellite Operator | Earth Observation Data | https://www.skyfi.com/ | Austin |
| UrbanSky | S | USA | Satellite Operator | Microsatellites (Microballoon) | https://www.urbansky.com/ | Denver |
| SaferPlaces | S | Italy | GIS / Spatial Analysis | Digital Twin for Flood Risk Intelligence | https://saferplaces.co/ | Rimini |
| 52Impact | S | Netherlands | GIS / Spatial Analysis | Mapping and Analytics | https://www.52impact.nl/ | Rotterdam |
| Flai | S | Slovenia | GIS / Spatial Analysis | Point Clouds | https://www.flai.ai/ | Ljubljana |
| EarthGenome | S |  | GIS / Spatial Analysis |  | https://earthgenome.org/ |  |
| Xplore | M | USA | Satellite Operator | Space and Satellite-As-A-Service | https://www.xplore.com/index.html | Redmond|
| Kayross | L | France | GIS / Spatial Analysis | Earth Observation Analytics | https://www.kayrros.com/ | Paris |
| Presagis | L | Canada | GIS / Spatial Analysis | Digital Twin | https://www.presagis.com/en/ | Montreal |
| Seqana | S | Germany | GIS / Spatial Analysis | Agriculure/Soil/Carbon | https://www.seqana.com/ | Berlin |
| Duality | M| USA | GIS / Spatial Analysis | Digital Twin | https://www.duality.ai/ | San Mateo |
| OriginDigital | M| England | Digital Farming | Agriculture | https://digital.originenterprises.com/ |Didcot |
| EarthConsole | S | Italy | Earth Observation |  | https://earthconsole.eu/ | Rome |
| Jua | M | Switzerland | Earth Observation | Weather Data | https://www.jua.ai/ | Freienbach |
| DynaCrop | S | Czech Republic | Digital Farming | Satellite Crop Monitoring | https://dynacrop.space/en/ | Brno |
| OneSky | M | USA | UAV / Aerial | UAV modeling and simulation tools |  https://www.onesky.xyz/ | Exton |

**Comment by chrieke** [comment]
Wow Naman, that is awesome!! Thank you for the big contribution! Will check next week.

**Comment by chrieke** [comment]
@seedlit You want to do a PR as contributor?
[README.md](https://github.com/chrieke/awesome-geospatial-companies/files/11399692/README.md)

Removed a few which imho didn't fit and moved some to the "to evaluate issue", but wanted to make this happen now, still plenty :) Thank you a lot!

**Comment by seedlit** [comment]
@chrieke thanks! :) 
Unfortunately, I am getting following error. Perhaps, you need to update permissions?

command:
`git push --set-upstream origin some_more_companies`

error:
`remote: Permission to chrieke/awesome-geospatial-companies.git denied to seedlit.
fatal: unable to access 'https://github.com/chrieke/awesome-geospatial-companies.git/': The requested URL returned error: 403 `

**Comment by chrieke** [comment]
Hm, looks fine. Could you doublecheck please that none of the usual issues e.g. [this](https://github.com/trilbymedia/grav-plugin-git-sync/issues/39#issuecomment-517804081) or [that](https://github.com/trilbymedia/grav-plugin-git-sync/issues/39#issuecomment-538867548)?
