### ISSUE TITLE
Add Egyptian Comapny

### ISSUE THREAD

**Issue by Reslan-Tinawi** [chrieke/awesome-geospatial-companies#56]
Hello there,

I want to add the information for a company based in Egypt:

1. Company: [Visual and AI Solutions (VAIS)](https://vais.ai/)
2. Size: Small (6 employees according to [LinkedIn](https://www.linkedin.com/company/visual-and-ai-solutions/))
3. Country and City: Egypt,  Giza.
4. Focus: Digital Farming

Note: I'm not affiliated with the company in any way, I just follow it on LinkedIn and thought it would be useful to add to this list.

**Comment by chrieke** [comment]
Thanks, added, will show in next iteration.
