### ISSUE TITLE
Radar and F4 Maps

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#61]
Hiya, 

2 more companies that do various geospatial things:
- https://www.f4map.com/
- https://radar.com/

Cheers!

**Comment by chrieke** [comment]
Thanks @dchirst 
Added radar, leaving off f4map. Belongs to https://www.f4-group.com/ which develops videogames & 3d mapping, but a bit strange website & half the people on linkendin are hidden profiles.
