### ISSUE TITLE
Additional Geospatial companies to consider 🛰️🌍

### ISSUE THREAD

**Issue by geospatialsam** [chrieke/awesome-geospatial-companies#66]
Hey! I'm Sam, a Recruiter situated in London with a focus on working with startups/scaleups in the field(s) of Geospatial, Earth Observation and Remote Sensing. Here are some additional companies for the list: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SAMWAR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SAMWAR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

1Spatial
--
52impact
Advanced Infrastructure
Agreed Earth
AGVOLUTION GmbH
AirForestry
Aistech Space
Alcis Geo
ALL.SPACE
Ariadne
ASDRO
Aurea Imaging
Bayanat
Blackshark.ai
Blue Sky Analytics
CARTO
Citymapper
cloudeo
CollectiveCrunch
con terra GmbH
constellr
Deep Planet
Downforce Technologies
Dryad Networks
Earth Blox
Earth Science Analytics AS
Earthwave
Ecometrica
eLEAF
Eoliann
EOMAP
FarmTrace
Geo Engine
GeoJunxion BV
Geollect
GEOLYTIX
Geospatial Insight Limited
Geotree
GlobalTrust Ltd
HiDef Aerial Surveying Limited
Hyperplan
ICEYE
IQGeo
Kamma
Kleffmann Digital RS
Kuva Space
LandHawk
LandTech
Living Map
Lobelia Earth
Map of Ag
Mapcreator
Meteory
NatureMetrics
NavVis
Nofence
OCELL
OKAPI:Orbits
Olvin
Omega Crop
Open Cosmos
Orbital Eye
Origin Digital
OroraTech
Overstory
Picterra
Reflex Aerospace
Restor
Rezatec
SarVision
SATAVIA
Satelligence
Satellogic
SatVu
Scopito
Sensing Clues
Seqana
Skytree
Solenix
Source.ag
Space Intelligence
SpaceSense
Spatial Eye
Spatial Insight
Stenon
Sylvera
Targomo
Tensing
Teralytics
Topolytics
TOPseven
Treefera
triply
UNIQUE forestry and land use   GmbH
UP42
Urban Intelligence
Uzufly
Verna
Vexiza
VISTA Remote Sensing in   Geosciences GmbH
xarvio Digital Farming   Solutions
AgriSound
AIRMO
apic.ai
CarbonFarm
Cirium
Dendra Systems
D-Orbit
Electricity Maps
EnduroSat
Exotrail
ForestSAT AS
Geoprospectors GmbH
Nala Earth
Nomoko
north.io GmbH
Pachama
Pina Earth
Planetek Italia
Rosa.io
ruumi
sat:io
Skyseed
Spacept
Spoor
ThrustMe
UnseenLabs
VU.CITY
Zulu Ecosystems
CelsiusPro
CetoAI
Climate X
Fathom
FloodFlash
Intelligent AI Limited
JBA Risk Management
McKenzie Intelligence Services Ltd
Mitiga Solutions
Mitigrate
Ombrea
Previsico
Reask
SaferPLACES
4EI
7 Satya
Addland
Addresscloud
AVUXI
CGG Satellite Mapping
Climate Risk Services
Continuum Industries
Correntics
Terrabotics
EarthSense
Emu Analytics
EOLAS Insight
GeoLegalTech
geOps
GeoSmart Information
HydroScan Group
Landstack
Map Impact
Mapular
Meridia
nPlan
Orbio Earth
pass_by
Pointr
PowerMarket
Preligens
Risilience
Satellite Applications Catapult
Searchland
Sensat
Single.Earth
Svarmi
Terra Preta
VertiGIS
Vexcel Imaging
CropX Technologies
Envitia
GeoVille Information Systems and Data   Processing GmbH
Global Surface Intelligence
Murphy Geospatial
PropEco
Vyoma
Wakeo
Ageoce Solutions
Cosmo Tech
Geode-solutions
Aerospacelab
FloodTags
SatSense Limited
Martello
Absolut Sensing
Aegir Insights
Ch.AI
Argus
ExtraMile Cloud
PROMÉTHÉE Earth Intelligence
Mytraffic
eOdyn
KERMAP
Sen
General System
Wegaw
Mantle Labs
MindEarth
Sateliot
Neuralio A.I.
GeoCento Ltd
Rivada Space Networks
Kanop
UnseenLabs
GEOSAT
INVERTO
Land Life
Jeev
GLOBHE
Skyqraft
nadar
Vaarst
Maya Climate
KERMAP
Kayrros
GlobalTrust Ltd
EnliteAI GmbH
Ellipsis Drive
textomap
TravelTime
nFrames
Yara International
AxessImpact

</body>

</html>

**Comment by chrieke** [comment]
That's awesome @geospatialsam thank you so much! Had a quick glance and there is a ton which aren't on the list yet. Will start adding them soon!

**Comment by chrieke** [comment]
Added the first ~ 35, so many, splitting it up :)

Remaining to evaluate:
ThrustMe, UnseenLabs, VU.CITY, Zulu Ecosystems, CelsiusPro, CetoAI, FloodFlash, Intelligent AI Limited, JBA Risk Management, Mitigrate, Ombrea, Reask, 4EI, 7 Satya, Addland, AVUXI, Climate Risk Services, Continuum Industries, Correntics, EOLAS Insight, GeoLegalTech, GeoSmart Information, HydroScan Group, Landstack, Map Impact, Meridia, pass_by, Pointr, PowerMarket, Searchland, Svarmi, Vexcel Imaging, CropX Technologies, Murphy Geospatial, PropEco, Vyoma, Wakeo, Ageoce Solutions, Cosmo Tech, Geode-solutions, FloodTags, Martello, Absolut Sensing, Aegir Insights, Ch.AI, Argus, ExtraMile Cloud, PROMÉTHÉE Earth Intelligence, Mytraffic, eOdyn, KERMAP, Sen, General System, Mantle Labs, MindEarth, Sateliot, Neuralio A.I., Rivada Space Networks, Kanop, INVERTO, Land Life, Jeev, GLOBHE, Vaarst, Maya Climate, KERMAP, EnliteAI GmbH, textomap, Yara International, AxessImpact

**Comment by chrieke** [comment]
Added the rest, another 30 or so! Thanks again!!!
