### ISSUE TITLE
Additional Geospatial Companies to Consider 🌍🛰️

### ISSUE THREAD

**Issue by geospatialsam** [chrieke/awesome-geospatial-companies#67]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SAMWAR~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SAMWAR~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Betterview
Descartes Labs
Gro Intelligence
Chloris Geospatial
Satelytics
Spexi Geospatial Inc.
Verisk
Care Weather Technologies
Arturo.ai
Ecopia Tech Corporation
Zesty.ai
Perennial
AiDash
EigenRisk Inc.
dClimate
Impact Observatory
Climate Engine
Astraea
EarthOptics
Rubicon Carbon
3vGeomatics
Arbol Inc.
MyRadar
Aclima Inc.
Waterplan
Orbital Insight
Umbra
Spire
ORBCOMM
SpaceKnow Inc.
Orbital Sidekick
Planet
Upstream Tech
TCarta
Patch
Pachama
WeatherStream, Ltd.
Sanborn
Tomorrow.io
CATALYST
Pano AI
SkyFi
PlanetiQ
Sidus Space
One Concern
Wyvern
SkyGeo
riskthinking.AI
Ursa Space Systems
Alpha Insights
Maxar Technologies
Geosite
CAPE Analytics
GeoOptics
Arable Labs, Inc.
HySpecIQ
KatRisk LLC
NUVIEW
EarthDaily Analytics
Array Labs, Inc.
Jupiter Intelligence
BlackSky
Hayden AI
EarthDaily Agro
Natrx
Loft Orbital
Hydrosat
ClimateAi
Floodbase
KorrAI
EOI Space
HawkEye 360
GHGSAT
Muon Space
Capella Space
Albedo
Development Seed
Pixxel
Earth Knowledge
Vitidore
Precisely
Felt
Tensorflight

</body>

</html>

**Comment by chrieke** [comment]
Nice! See more familar ones here at first glance, but still a treasure!!

**Comment by chrieke** [comment]
And that was another 16 companies. Awesome, thank you again Sam!
