### ISSUE TITLE
Add WEO from Luxembourg

### ISSUE THREAD

**Issue by thierryweo** [chrieke/awesome-geospatial-companies#69]
Hello thanks for this AWESOME list

We are a small Company from Luxembourg

WEO
Office size `S`
URL: https://weo-water.com
Address: 9 Rue du Laboratoire, 1911 Gare Luxembourg
Category: GIS / Spatial Analysis
What we do: Environmental Analytics for All from Space

**Comment by chrieke** [comment]
Added, thanks.
