### ISSUE TITLE
Please add Solafune from Japan

### ISSUE THREAD

**Issue by pkopparla** [chrieke/awesome-geospatial-companies#70]
Please include the following company in your list!

Company name: Solafune Inc.,
Categories: Geospatial data analytics and satellite data competitions
Office size: S (~15)
Office location: Tokyo, Japan
Website: https://company.solafune.com/
LinkedIn: https://www.linkedin.com/company/solafune/mycompany/
Twitter: https://twitter.com/solafune_inc

thank you,
pk

**Comment by chrieke** [comment]
Thank you, added.
