### ISSUE TITLE
2 more companies

### ISSUE THREAD

**Issue by dchirst** [chrieke/awesome-geospatial-companies#72]
Hey Christoph! 2 more companies for you to look at:

1. [Hivekit](https://hivekit.io/) - (Small) GIS / Spatial Analysis company doing workforce coordination. Based in UK and Germany with office in USA (kinda a remote company?)
2. [GeoCompas](https://geocompas.ai/) - (Small) EO and mapping data labelling company based in Peru. Spinout of DevelopmentSeed

**Comment by chrieke** [comment]
Thanks, added!
