### ISSUE TITLE
Company Description and Link updation of entry of Skyserve

### ISSUE THREAD

**Issue by arvind-subramanian** [chrieke/awesome-geospatial-companies#73]
<img width="808" alt="Screenshot 2024-05-06 at 11 29 00 AM" src="https://github.com/chrieke/awesome-geospatial-companies/assets/369012/9acc8d8e-89b8-4642-ae77-3c9be81c8a5b">

Please update the correct website : https://www.skyserve.ai/ 

Please update the description to : "Onboard AI for Satellites: Streamlined Edge Computing & MLOps for GeoAI"

**Comment by chrieke** [comment]
Thanks @arvind-subramanian updated the website, will be published in next update. 

I want to keep the descriptions as compact and "marketing-speech-free" as possible. Does "Edge Computing for satellite Onboard GeoAI & MLOps" work? Let me know if you have another suggestion
