### ISSUE TITLE
Consider Adding New Geospatial Startup: Galileo 

### ISSUE THREAD

**Issue by mitchellmaps21** [chrieke/awesome-geospatial-companies#78]
[Galileo](https://galileo.gisdata.io/) - Geospatial data discovery and management platform. Search over 1,890+ data sources spatially, with advanced filters, previews and data downloads to 5 file types

Size: Startup 5 Individuals
Categories: GIS/Geospatial
Based out of Orlando, UCF Incubator

**Comment by chrieke** [comment]
Added
