### ISSUE TITLE
PolArctic LLC

### ISSUE THREAD

**Issue by m-pavlock** [chrieke/awesome-geospatial-companies#8]
Hi! Came across this list, and it's definitely awesome!
I'm wondering if you could add our company, PolArctic LLC. We specialize in data science and oceanography , focused on sea ice modeling, nearshore mapping, and water quality mapping primarily using space based imagery and machine learning. 
Thanks! https://polarcticllc.com/

**Comment by chrieke** [comment]
Added, thank you!
